### ISSUE TITLE
Question: Restrict to files in PR

### ISSUE THREAD

**Issue by albertmink** [abaplint/actions-abaplint#26]
Can the GitHub Action be restricted to files in PR? Sometimes it no fun to get blamed for something that is for some reason in the repository.

Maybe something like

```YML
      ...
      - name: abaplint
        uses: abaplint/actions-abaplint@main
        with:
          files: ONLY_FILE_IN_PULL_REQUEST

```
